# Generated by Django 4.1.6 on 2023-02-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvrr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='genre',
        ),
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.ManyToManyField(to='vvrr.genre'),
        ),
    ]
